# Generated by Django 4.1.7 on 2023-03-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_image',
            field=models.ImageField(height_field='200', upload_to='productimg'),
        ),
    ]
